import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Script from 'next/script';
import Image from 'next/image';
import clsx from 'clsx';
import BottomTabs from '@/components/BottomTabs/BottomTabs';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Script src="https://telegram.org/js/telegram-web-app.js" />
      <body
        className={clsx(
          inter.className,
          "bg-[url('/background.png')] bg-cover min-h-screen flex flex-col theme-gold text-white"
        )}>
        <main className="flex flex-col flex-1">
          {children}
          <BottomTabs />
        </main>
      </body>
    </html>
  );
}
